### ISSUE TITLE
Compile error using CUDA thrust

### ISSUE THREAD

**Issue by BerndDoser** [treecode/Bonsai#31]
Compiling Bonsai master-branch with CUDA thrust support

`cmake -DUSE_MPI:BOOL=OFF -DUSE_THRUST:BOOL=ON ..`

crash during linking with

`/usr/local/cuda-7.5/include/thrust/system/cuda/detail/cub/device/device_radix_sort.cuh:158: multiple definition of 'thrust_sort_32b'
CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/bonsai2_slowdust_generated_build_tree.cu.o:/home/bernd/git/Bonsai_org/runtime/CUDAkernels/support_kernels.cu:25: first defined here
CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/bonsai2_slowdust_generated_compute_propertiesD.cu.o: In function 'thrust::detail::temporary_allocator<char, thrust::system::cuda::detail::tag>::allocate(unsigned long)':
/usr/local/cuda-7.5/include/thrust/system/cuda/detail/cub/device/dispatch/device_radix_sort_dispatch.cuh:922: multiple definition of 'thrust_sort_96b'
CMakeFiles/bonsai2_slowdust.dir/CUDAkernels/bonsai2_slowdust_generated_build_tree.cu.o:/home/bernd/git/Bonsai_org/runtime/CUDAkernels/support_kernels.cu:74: first defined here
collect2: error: ld returned 1 exit status`

**Comment by jbedorf** [comment]
Hi,

Thanks for the report, this has been fixed in commit 64636b9a5be2721118dc91382c15a0c69d3924ab

Jeroen

**Comment by BerndDoser** [comment]
Hi Jeroen,

Thanks for the fast response. It compiles now.

Bernd
