### ISSUE TITLE
Allocation errors on a V100

### ISSUE THREAD

**Issue by anthony-arnold** [treecode/Bonsai#39]
I consistently get cudaMalloc allocation errors when allocating the generic buffer. I think this is because the V100 is using 32 tree walk blocks per SM, and has 84 SMs. Using the preset values in node_specs.h, it ends up trying to allocate ~5.7 GB. While in theory there should be plenty of memory available on the device, I get consistent failures to allocate this array.

I've temporarily worked around it by reducing to 8 tree walk blocks per SM, but I imagine this will hurt performance. 

What would be the preferred way to reduce the size of the generic buffer so that allocation succeeds? Is reducing the number of tree walk blocks preferable, or perhaps I should reduce NTHREAD?

Or maybe I've missed something else entirely? Is there a fixed upper limit on contiguous array allocations for cuda? I wouldn't think so. It's possible that 6GB is just too big to find a contiguous block, but with the device practically empty I figured it should be possible.

**Comment by jbedorf** [comment]
Interesting. I'm not aware of there being a limit on the maximum memory allocation size, and 6GB should easily fit in that memory. I don't have access to a V100 so I can't test it out from my side. 

The reduction in tree walk blocks per SM will hurt performance, but so will reducing NTHREAD, probably even more so. 
Another thing that you can try is to lower: `LMEM_STACK_SIZE`  [here](https://github.com/treecode/Bonsai/blob/master/runtime/include/node_specs.h#L52).  The 'only'  problem with this is that you risk getting invalid results. This is size indicates how many tree nodes can be cached for further processing when going down the tree. If you have a very small opening angle then you will need a higher buffer size. However, if your angle is such that only a small fraction of the tree has to be traversed then you can safely lower that number. 

It would require a bit of trial and error to find which number works for you, also it might depend on the system that you are simulating if it will change over time. 

It might be worth to ask NVIDIA if there is a limit on the maximum memory, or try to test the allocation in a standalone program that does nothing else than allocating the large buffer. If it works in a standalone program then you can consider moving the allocation of generalBuffer1 to an earlier part of the program, so from [here](https://github.com/treecode/Bonsai/blob/master/runtime/src/build.cpp#L64) to, for example, [here](https://github.com/treecode/Bonsai/blob/master/runtime/src/build.cpp#L14) in the hope that the memory is not fragmented yet and that the allocation succeeds.
