### ISSUE TITLE
Where to find galactics.parallel fork of John Dubinsky galactics code?

### ISSUE THREAD

**Issue by fizxmike** [treecode/Bonsai#4]
The readme in the runtime folder mentions a file "galactics.parallel.tar.gz" do you know where one could download it?

**Comment by derkreature** [comment]
Was there a status update for this?

**Comment by egaburov** [comment]
Hi,

I saw you last achievements, and I think you need to keep up the good work! Here is some helpful information for you <http://powethosi.henriettethehorseshoecrab.com/xyjivudu>

egaburov@dds.nl
