### ISSUE TITLE
CMake error on master Bonsai

### ISSUE THREAD

**Issue by twobombs** [treecode/Bonsai#41]
Hi,

I would like to see Bonsai so I compiled it and I got this error:
![Screenshot from 2020-11-06 09-46-53](https://user-images.githubusercontent.com/12692227/98345975-4806c900-200d-11eb-8105-dbb516580c3c.png)

I retried with production values ( without the OGL handle ) and got the same error.
I'm on Ubuntu 20.04, I added the CMakeOutput.log, i can't find what's going wrong here.

[CMakeOutput.log](https://github.com/treecode/Bonsai/files/5500171/CMakeOutput.log)

**Comment by jbedorf** [comment]
Hi, 

You have to execute the `cmake` command from the "runtime" folder and not from the "tools" folder: https://github.com/treecode/Bonsai/tree/master/runtime
