### ISSUE TITLE
missing: mpi.h

### ISSUE THREAD

**Issue by twobombs** [treecode/Bonsai#42]
next up:

cmake sets the enviroment yet make causes an include fail : mpi.h

installed anything that I could find on mpi.h, but to no avail. again on ubuntu 20.04

![Screenshot from 2020-11-06 20-08-30](https://user-images.githubusercontent.com/12692227/98405158-b1b1c200-2063-11eb-9b07-4f7d689ca9ff.png)

Any ideas here ? 
( background:  I'm trying to build this project to see if I can use the output of Qrack, a quantum computer simulator, on the nbody functions. )

**Comment by jbedorf** [comment]
If you want MPI support you have to specify the MPI compiler as follows:
`Using MPI under linux: cmake -DCMAKE_CXX_COMPILER=mpicxx`

If you don't want MPI support (so single GPU only), then disable the MPI options in the CMake config via the `ccmake` program, eg:
`ccmake .`

**Comment by twobombs** [comment]
Thanks, will look into my options. Looking into using a K80 Tesla ( dual GPU )
