### ISSUE TITLE
GCC 8+

### ISSUE THREAD

**Issue by twobombs** [treecode/Bonsai#43]
Last one for tonight: is it correct I need to downgrade GCC to compile ? As that might be a killer... ;(

![Screenshot from 2020-11-06 20-47-43](https://user-images.githubusercontent.com/12692227/98408448-13c0f600-2069-11eb-9498-0f27cdb77cb5.png)

![Screenshot from 2020-11-06 20-50-46](https://user-images.githubusercontent.com/12692227/98408642-6b5f6180-2069-11eb-8116-aa5cfaff5ddf.png)

**Comment by jbedorf** [comment]
You need to install a CUDA version that is compatible with the GCC version that you want to use. So yes, either downgrade GCC or upgrade CUDA. You can usually install an alternative GCC version next to the system default.
