### ISSUE TITLE
GL compilation

### ISSUE THREAD

**Issue by twobombs** [treecode/Bonsai#44]
Compiling with the following settings for OpenGL Display
![Screenshot from 2020-11-29 11-25-51](https://user-images.githubusercontent.com/12692227/100540521-a94d4100-3235-11eb-9ac5-9a94c53fc201.png)

Gives this error at make:
![Screenshot from 2020-11-29 11-23-42](https://user-images.githubusercontent.com/12692227/100540461-668b6900-3235-11eb-8689-da9c424a8f66.png)

Can't find the lib that represents glLightfv for Ubuntu 20.04, seems to be an GL function. Without the GLVN directive I get this error.

![Screenshot from 2020-11-29 11-34-48](https://user-images.githubusercontent.com/12692227/100540727-f67de280-3236-11eb-943c-8d5dba619253.png)

**Comment by jbedorf** [comment]
I'm not familiar with the `glLifghtfv` error. Maybe some function or version has changed since the last time I ran this (I never used Ubuntu 20.04 for this, and I'm not sure which version of the OpenGL libraries it comes with). 

The second error can be solved by downloading and recompiling the GLEW library with the `-fPIE` directive. I think this comes forth from trying to combine both the MPI directive and the OpenGL one. For those use-cases you need a recompiled GLEW library to replace the version that is packaged with the repository.

**Comment by twobombs** [comment]
Thanks for the response. I've disabled the MPI section but the error still occurs. 

![Screenshot from 2020-11-30 15-19-57](https://user-images.githubusercontent.com/12692227/100628099-c100f400-331f-11eb-8037-0a89813868d9.png)

![Screenshot from 2020-11-30 15-19-26](https://user-images.githubusercontent.com/12692227/100628122-c8280200-331f-11eb-8f08-e20e5b8c36fe.png)

Because this is for usage on top of the NV CUDA 11 images in Docker I'm trying to keep this as clean as possible. No manual edits and such.

Losing MPI in that process would not be a problem because a GPU can be selected as a separate resource in nvidia-docker.
Well... will try and see where this GLlightfv error comes from then

Tnx for pointing the direction. :)

**Comment by jbedorf** [comment]
Ok that is strange, I just tried it out on an older Ubuntu machine and the above worked. I'll see if I can use a VM machine to test this, which version of CUDA is being used here?

**Comment by twobombs** [comment]
Cuda 11.1

**Comment by jbedorf** [comment]
I was unable to reproduce the `glLifghtfv` error that you mentioned, but the other error can be fixed as follows:
```
cd runtime/lib
mv glew glew_temp
mv linux_fpic_glew glew
```
Bonsai comes with a glew library that is compiled with the right flags, it's just not set as default. I tested this out under Ubuntu 20.04/CUDA11.1 and it builds.

**Comment by twobombs** [comment]
Thank you for pointing this out. I had to rename linux to linux_temp and linux_fpic_glew to linux. Then it compiled succesfully. Now I can start to put this into a container image. I'll let you know when there is significant progress. Thanks again.
