### ISSUE TITLE
Segfault Linking GL? context

### ISSUE THREAD

**Issue by twobombs** [treecode/Bonsai#45]
I've integrated Bonsai into the Qracknet docker environment ( twobombs/qracknet:bonsai ) and find that there are segfaults whilst linking in the GL context for the GL compiled version of Bonsai. System is running inside a container with a software FB and software GL, but displays a similar error running directly on the host. I think Bonsai requires an hardware accelerated  NVidia GL and FB ? 

Will work further on narrowing down the cause of this crash. Compiled without GL works both inside the container and on the host. But we want all the bells and whistles, now won't we ? :) 

<img width="1230" alt="Screenshot 2020-12-13 at 13 26 23" src="https://user-images.githubusercontent.com/12692227/102012101-b8a9af80-3d48-11eb-88f3-6eb86533d5e6.png">

**Comment by jbedorf** [comment]
Looking at the output it seems this is the reason: 
`error: linking with uncompiled/unspecialized shader`
Which originates from here: https://github.com/treecode/Bonsai/blob/master/runtime/renderer/GLSLProgram.cpp#L203

I've only ever tested the OpenGL features on an NVIDIA GPU with a (virtual) monitor attached. Without monitor I doubt it will run.

**Comment by twobombs** [comment]
Suspected such a case, will look into it. Tnx :)
( will reopen when progress is made )

**Comment by twobombs** [comment]
I've worked around the SegFault link error, worked out the incompatibilities between X11 version in docker and on the host. Binded the host X socket so it can run x apps inside the container, and through the $DISPLAY on the host. The render window is opened and visible, but then smokerenderer.cpp is segfaulting. I feel I'm almost there, any ideas what might be up here ?

![Screenshot from 2020-12-19 12-29-08](https://user-images.githubusercontent.com/12692227/102688250-6d324e00-41ed-11eb-9491-3d3ffbc52370.png)


![Screenshot from 2020-12-19 12-09-11](https://user-images.githubusercontent.com/12692227/102688225-2e9c9380-41ed-11eb-869b-52d0897cf36e.png)

**Comment by jbedorf** [comment]
Did you set "ulimit -s unlimited" inside the Docker container/run script?
If that's not the reason then try to get a core dump such that the backtrace can be inspected to help narrow it down. You might have to run "ulimit -c unlimited"  before launching bonsai to get your environment to generate the core dump.
It looks like the container already runs a core dump, so next step would to inspect/open it with `gdb`.

**Comment by twobombs** [comment]
![Screenshot from 2020-12-20 10-46-27](https://user-images.githubusercontent.com/12692227/102710167-687ea000-42a8-11eb-9fe5-a203f42ad468.png)

What can I say, other then: Thank you very much ! :1st_place_medal:  I'll tune, integrate and commit this into the qracknet:bonsai stack. Whilst on this topic: you won't happen to know a tool that can generate/convert to .tipsy file ? :)  i've got oodles of quantum cosmoslogy data desperately waiting for a visalisation :eyes:

**Comment by jbedorf** [comment]
Great!

You can find some conversion tools in this folder: https://github.com/treecode/Bonsai/tree/master/tools/IO  and or repurpose the bonsai code here:
https://github.com/treecode/Bonsai/blob/master/runtime/src/tipsyIO.cpp#L47

**Comment by twobombs** [comment]
@jbedorf I've found time to start playing with nbody file formats and conversion. I see that I need to add more parameters to some of the converson tools. The minimum additional requirement seems to be nDomain, it this supposed to be a number, a list or a predefined set of parameters like a mask of some sorts ?

![Screenshot from 2021-01-03 11-33-03](https://user-images.githubusercontent.com/12692227/103476615-5d9b3380-4daf-11eb-9db6-d13b478a93f4.png)

My goal is to import .csv with ~55k data points of vacuum space quantum fluctuation data ( each point 27 qubits [3x3x3] wide )   and convert this to a format that bonsai can use. That point however is some way off, at first I would like to convert existing tipsy file formats to CSV to see what additional data an csv import needs to have. ( location, type )

by the way: bonsai is very fast and very compact in memory usage compared to other programs. And it generates some  stunning views :)

**Comment by jbedorf** [comment]
In this case 'tipsy2bonsai' means converting a tipsy file into a Bonsai specific file format. That file-format is designed to use MPI-IO for optimal usage during large parallel simulations. So this converter was written with that in mind, as in it can convert multiple tipsy files into a single 'bonsai' file. The `nDomains` refers to the number of parallel written tipsy files to use to convert into a single one If you're just trying to convert a single tipsy file then you can just set it to '1'.

The tipsy file format definitions can be found here: https://github.com/treecode/Bonsai/blob/master/tools/IO/tipsydefs.h 
We're using the star_particleV2 and dark_particleV2 constructs.

**Comment by twobombs** [comment]
<img width="1025" alt="Screenshot 2021-01-04 at 19 46 47" src="https://user-images.githubusercontent.com/12692227/103570086-bad6d800-4ec8-11eb-95e5-9459b61a9668.png">

segfaulting on conversion of the included sample, any ideas ? created this with a make in /Bonsai/tools/IO

**Comment by jbedorf** [comment]
Looks like the argument checking is broken, try it like this: `./cvt_tipsy2bonsai ../../runtime/model3_child_compact.tipsy  1 out.bonsai 1 1`

**Comment by twobombs** [comment]
As expected, he extra '1 1' did it. Thanks. Would you perhaps have some documentation for the bonsai file format  ? It seems that that file format supports the IO tooling the best, so far it looks that I'll be importing from cvs to amuseacsii and then to bonsai file format. Might be a good thing to convert from cvs straight into bonsai as the information pipeline needs to be as short as possible because of the large amount and streaming of data coming from the quantum cosmos calculation pool.

**Comment by twobombs** [comment]
I have written a conversion script at [https://github.com/twobombs/qracknet/blob/master/scripts/makebonsai.sh](https://github.com/twobombs/qracknet/blob/master/scripts/makebonsai.sh) and I see that there are differences in the notation of the values. Could/can someone point out what the position of the variables are in the converted model3_child_compact bonsai hex file ? This would help  great deal in setting the variables in correct order.

<img width="1070" alt="Screenshot 2021-02-27 at 13 34 11" src="https://user-images.githubusercontent.com/12692227/109387249-8e579f00-7900-11eb-83c1-3ab6b5a2dddb.png">

i think there is a big endian notation might be a thing going on in the first value, the directional speed for the imported quantum points are all zero at the moment. 

<img width="1073" alt="Screenshot 2021-02-27 at 13 45 03" src="https://user-images.githubusercontent.com/12692227/109387528-2e61f800-7902-11eb-82e5-534aba9fa33a.png">
^ the converted file from ascii output to binary hex


before the file gets converted to binary, this is what the variables look like in hex-ascii. 
it has ID, x, y, z, m, zd,yd,zd  preceded at the top with the amount of points ( only a small subset of the actual quantum data )

<img width="1019" alt="Screenshot 2021-02-27 at 13 45 32" src="https://user-images.githubusercontent.com/12692227/109387547-4e91b700-7902-11eb-9d8a-ab2712890612.png">

**Comment by twobombs** [comment]
> I've only ever tested the OpenGL features on an NVIDIA GPU with a (virtual) monitor attached. Without monitor I doubt it will run.

Forgot to mention : with the containerized [version](https://github.com/twobombs/thereminq-bonsai/tree/main) we are able to not only render and calculate on different CUDA devices but also redirect the output to a radeon and/or Intel card where the screen is attached
