### ISSUE TITLE
Feature: colour in object declaration

### ISSUE THREAD

**Issue by twobombs** [treecode/Bonsai#46]
Hi wonderfull people of the Bonsai project,

I am working on feeding Bonsai a whole bunch of  quantum data and would like to add a colour to the imported objects. 
AFAIK stars have colours too, is this something that crossed someone's mind to do during recent times or is it ouside the context of this project ?

Its absence is not a killer in that "I needs it", but "I do wants it" because it is an easy and intuitive way to see what the quantum density is for an imported datapoint, and might be interesting to look at from a stellar perspective ?

Just thinking out loud.

**Comment by jbedorf** [comment]
The rendering code has provisions for colouring objects, for example [here](https://github.com/treecode/Bonsai/blob/master/runtime/CUDAkernels/depthSort.cu#L116) and [here](https://github.com/treecode/Bonsai/blob/8904dd3ebf395ccaaf0eacef38933002b49fc3ba/tools/bonsaiRenderer/particles/renderloop.cpp#L391).

You should be able to piggy back on those parts as long as you are able to get the right color selection/mapping there, e.g. via the 'idtype'. Adding additional variables requires changes throughout the code as the arrays are shuffled multiple times so you would have to keep track of all of that.  The IDType is 64bit so there should be room to play with.

**Comment by twobombs** [comment]
Thank you for the directions, I will look into this. For now I'm planning to just use type 2 and get the stuff imported. The colour scheme need not to be more then 32 bits as its the current maximum of the simulation.
